### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735914655

### CODE REVIEW

**Comment by bissenbay** [comment]
@harshad16 PTAL https://github.com/thoth-station/s2i/pull/48/commits/969ec0c461846f205b44d6d8af99e1d760cfddce

**Comment by bissenbay** [comment]
@fridex @harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Review by fridex — APPROVED** [review]
:100:

**Pull request merged**
