### PR TITLE
No build to trigger

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@harshad16 Also, zuul is not merging PRs in this repo automatically. Could you please have a look please? The config file seems to be present

https://github.com/thoth-station/zuul-config/blob/master/zuul/s2i.yaml

**Review by harshad16 — APPROVED** [review]

**Comment by harshad16** [comment]
@fridex, the project should have the zuul support now. 
Added it in the list of project to be managed by zuul. 
sorry for the delay :peace_symbol:

**Comment by harshad16** [comment]
recheck

**Comment by fridex** [comment]
> @fridex, the project should have the zuul support now.
> Add it in the list of project to be managed by zuul.
> sorry for the delay

Awesome, thanks! :clap: :+1:

**Pull request merged**
